# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
inhibit_all_warnings!
use_frameworks!

target 'wa.me' do
  # Comment the next line if you don't want to use dynamic frameworks
  # Pods for wa.me
  #https://developers.google.com/admob/ios/quick-start
  pod 'Google-Mobile-Ads-SDK'
  
  #https://github.com/marmelroy/PhoneNumberKit
  pod 'PhoneNumberKit'
  
  #https://github.com/AssistoLab/DropDown
  pod 'DropDown'
  
  #https://github.com/Skyscanner/SkyFloatingLabelTextField
  pod 'SkyFloatingLabelTextField'
  
  # https://github.com/hackiftekhar/IQKeyboardManager
  pod 'IQKeyboardManagerSwift'
  
  pod 'RxCocoa'
  pod 'RxSwift'
  target 'wa.meTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'wa.meUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
         end
    end
  end
end
